server:
   port: 8080

logging:
    path: logs
    file: mylog.log


spring:
   application:
          name: report
   datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://192.168.0.12:3306/course?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
       username: root
       password: 199488

mybatis:
    type-aliases-package: com.course.model
    mapper-locations:
       - mapper/*
